2024-03-10 17:52:32,961 INFO Storage_lib.py'' <module> 228 :: ['drive /dev/sdb has not enough space for creating partition, remaining space : 1G you are given : 100G']
2024-03-10 17:54:52,090 INFO Storage_lib.py'' <module> 228 :: [[]]
2024-03-10 17:55:16,363 INFO Storage_lib.py'' <module> 228 :: [('\nWelcome to fdisk (util-linux 2.37.2).\nChanges will remain in memory only, until you decide to write them.\nBe careful before using the write command.\n\n\nCommand (m for help): Partition type\n   p   primary (1 primary, 0 extended, 3 free)\n   e   extended (container for logical partitions)\nSelect (default p): Partition number (2-4, default 2): Partition number (2-4, default 2): First sector (209717248-585937499, default 209717248): First sector (209717248-585937499, default 209717248): First sector (209717248-585937499, default 209717248): Last sector, +/-sectors or +/-size{K,M,G,T,P} (209717248-585937499, default 585937499): \nCommand (m for help): \n', "The device contains 'linux_raid_member' signature and it may remain on the device. It is recommended to wipe the device with wipefs(8) or fdisk --wipe, in order to avoid possible collisions.\nValue out of range.\nValue out of range.\nValue out of range.\n"), []]
2024-03-10 17:55:41,370 INFO Storage_lib.py'' <module> 228 :: [["Created a new partition 1 of type 'Linux' and of size 10 GiB : /dev/sdg1"]]
2024-03-10 17:56:27,259 INFO Storage_lib.py'' <module> 228 :: [["Created a new partition 2 of type 'Linux' and of size 20 GiB : /dev/sdg2"]]
2024-03-10 17:56:56,853 INFO Storage_lib.py'' <module> 228 :: list index out of range
2024-03-10 17:57:48,460 INFO Storage_lib.py'' <module> 228 :: ['unavailable partitions :: remaining partitions are only 0 you are given 2']
2024-03-10 17:59:00,388 INFO Storage_lib.py'' <module> 228 :: [' In drive /dev/sdg , extended partition not available create one extended partition']
2024-03-10 17:59:37,641 INFO Storage_lib.py'' <module> 228 :: [["Created a new partition 1 of type 'Extended' and of size 200 GiB : /dev/sdg1"]]
2024-03-10 18:00:32,756 INFO Storage_lib.py'' <module> 228 :: ["Created a new partition 5 of type 'Linux' and of size 2 GiB", "Created a new partition 6 of type 'Linux' and of size 2 GiB", "Created a new partition 7 of type 'Linux' and of size 2 GiB", "Created a new partition 8 of type 'Linux' and of size 2 GiB", "Created a new partition 9 of type 'Linux' and of size 2 GiB"]
2024-03-10 18:01:53,718 INFO Storage_lib.py'' <module> 228 :: [["Created a new partition 2 of type 'Linux' and of size 2 GiB : /dev/sdg2"]]
2024-03-10 18:02:58,339 INFO Storage_lib.py'' <module> 228 :: [('\nWelcome to fdisk (util-linux 2.37.2).\nChanges will remain in memory only, until you decide to write them.\nBe careful before using the write command.\n\n\nCommand (m for help): Partition type\n   p   primary (1 primary, 1 extended, 2 free)\n   l   logical (numbered from 5)\nSelect (default p):    p   primary (1 primary, 1 extended, 2 free)\n   l   logical (numbered from 5)\nSelect (default p):    p   primary (1 primary, 1 extended, 2 free)\n   l   logical (numbered from 5)\nSelect (default p): \nUsing default response p.\nPartition number (3,4, default 3): Partition number (3,4, default 3): Partition number (3,4, default 3): First sector (423626752-976773167, default 423626752): \nCommand (m for help): \n', 'Value out of range.\nValue out of range.\nValue out of range.\nValue out of range.\n'), []]
2024-03-10 18:03:35,202 INFO Storage_lib.py'' <module> 228 :: ['extended partition of /dev/sdg not have enough space, you have only 190G you are given 200G']
2024-03-10 18:05:17,289 INFO Storage_lib.py'' <module> 228 :: ["'/dev/sdg,/dev/sdf' drive is not found in server. Available drives['/dev/sda', '/dev/sdb', '/dev/sdc', '/dev/sdd', '/dev/sde', '/dev/sdf', '/dev/sdg', '/dev/sdh']"]
2024-03-10 18:06:07,653 INFO Storage_lib.py'' <module> 228 :: [('\nWelcome to fdisk (util-linux 2.37.2).\nChanges will remain in memory only, until you decide to write them.\nBe careful before using the write command.\n\n\nCommand (m for help): Partition number (3-128, default 3): Partition number (3-128, default 3): Partition number (3-128, default 3): First sector (34-585937466, default 34): First sector (34-585937466, default 34): First sector (34-585937466, default 34): Last sector, +/-sectors or +/-size{K,M,G,T,P} (34-2047, default 2047): \nCommand (m for help): \n', "This disk is currently in use - repartitioning is probably a bad idea.\nIt's recommended to umount all file systems, and swapoff all swap\npartitions on this disk.\n\nValue out of range.\nValue out of range.\nValue out of range.\nValue out of range.\n"), []]
2024-03-10 18:06:29,602 INFO Storage_lib.py'' <module> 228 :: [('\nWelcome to fdisk (util-linux 2.37.2).\nChanges will remain in memory only, until you decide to write them.\nBe careful before using the write command.\n\n\nCommand (m for help): Partition number (3-128, default 3): Partition number (3-128, default 3): Partition number (3-128, default 3): First sector (34-585937466, default 34): First sector (34-585937466, default 34): First sector (34-585937466, default 34): Last sector, +/-sectors or +/-size{K,M,G,T,P} (34-2047, default 2047): \nCommand (m for help): \n', "This disk is currently in use - repartitioning is probably a bad idea.\nIt's recommended to umount all file systems, and swapoff all swap\npartitions on this disk.\n\nValue out of range.\nValue out of range.\nValue out of range.\nValue out of range.\n"), []]
2024-03-10 18:07:03,702 INFO Storage_lib.py'' <module> 228 :: [["Created a new partition 3 of type 'Linux' and of size 20 GiB : /dev/sdg3"], ["Created a new partition 3 of type 'Linux' and of size 20 GiB : /dev/sdf1"]]
2024-03-10 18:18:19,546 INFO Storage_lib.py'' <module> 270 :: ['used :1260900', 'free :137471972']
2024-03-10 18:23:21,507 INFO Storage_lib.py'' <module> 228 :: [WinError 10060] A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond
